### ISSUE TITLE
Hey I might be able to help with this one!

### ISSUE THREAD

**Issue by DWW256** [calband/calchart-redesign#1]
Hi!  I'm the guy who wanted to see CalChart make it to Linux, but I have no problems with it being a web app!  I thought I'd let you know that I do know _some_ Vue, so I might be able to actually help with this one if you need something!  Do note that I'm not really experienced with programming, though, and I'm quite busy...but I'll still see if I can help.  So...what still needs to be done?  And are you using Vuex or Vue Router or any of those fancy things?

**Comment by MichaelTamaki** [comment]
@DWW256 Hey! Yes, we've started a redesign of CalChart for the web. It's getting more and more difficult to maintain native apps on Windows and Mac, so a web version seems to be the best option for compatibility. The current goal is to have this ready by Dec. 2020. See this repo for the work that has been done by Brandon last year: https://github.com/calband/calchart-redesign-old

If you're interested in helping development, we can add you to our Slack! Can you reach out to calband-compcomm@lists.berkeley.edu? The current computer coordinator can add you to it.
