### ISSUE TITLE
Set the shows to have beats be [0, N)

### ISSUE THREAD

**Issue by rmpowell77** [calband/calchart-redesign#100]
From our discussion, we should have shows use beat 0 as the "hup", and beat 1 is the first step off position 0.  So therefore each sheet should go from beat 0 to N-1, and when you get to beat N go to the next sheet at beat 0.

**Comment by MichaelTamaki** [comment]
Note: Calchart-viewer uses "Hup!" to represent "Beat 0" https://calband.github.io/calchart-viewer

## What does the last beat of each stuntsheet look like?

Turns into "Hup!" of the next stuntsheet.

## What should the last stuntsheet look like? 

A 0 or 1 beat stuntsheet?

## How will flows be represented?

An array of the "Hup!" beat to the last beat of the stuntsheet. It contains information about the dot's position, the dot's direction, and the dot's marching type. Later, this can be used to draw sprites or something!

We can add a verification that the last beat of the flow matches the dot's position in the next stuntsheet. The last beat is not shown in the UI though, as it's represented by the "Hup!" beat of the next stuntsheet... Or this could be used to say "This is where the dot is supposed to end up, this is where dot is ending up now".

However, what if the last stuntsheet if a movement? For example, march north 8 beats doesn't require knowledge of the last position.

## How are shows made?

Make the formations, highlight where perc/basses are, then work on the transitions.

**Comment by rmpowell77** [comment]
I think this was fixed with #125?
