### ISSUE TITLE
Re-do how dots connect to each other across stuntsheets

### ISSUE THREAD

**Issue by MichaelTamaki** [calband/calchart-redesign#103]
## The problem

`dot.dotLabelIndex` isn't an effective way to connect dots between stuntsheets. An example:

SS - "Stuntsheet"

- SS 1 Dot 1 has `dotLabelIndex` 99
- SS 1 Dot 2 has `dotLabelIndex` 1
- SS 2 Dot 1 has `dotLabelIndex` 99
- SS 2 Dot 2 has `dotLabelIndex` 1
- SS 3 Dot 1 has `dotLabelIndex` 99

Then connect SS 1 Dot 1 with SS 2 Dot 2.

- SS 2 Dot 1 and SS 3 Dot 1 are still connected. They need a new `dotLabelIndex` that doesn't collide with another dot. If there's a SS 4 +, then would need to go through the entire chain of dots to update
- SS 1 Dot 2 no longer has a pairing with a dot in SS 2. The `dotLabelIndex` should be set to `null`. But what if there was a stuntsheet before where a dot was connected to this dot? Then the dots in the chain before SS 1 Dot 2 would need a new `dotLabelIndex` that doesn't collide with another dot... etc.

## Possible solution

Give `Dot` a new field `id` and `connectedDotId`. `id` is an integer that is guaranteed to be unique within a stuntsheet. `connectedDotId` refers to a dot's id in the next stuntsheet that it is connected to.

Give `StuntSheet` a new field `nextId`. This is an integer to assign to the next dot created and gets iterated.

**Comment by rmpowell77** [comment]
If I recall, CalChart3.1 has the concept of Dot label indices, where each point could refer to a specific label.  But over time I found that this was cumbersome and not really useful. We went with the solution that a points offset in the array was basically it's index for the label.  And that works pretty well.

One reason to think we need a label index concept is if we want to relabel the dots.  But in reality you don't relabel dots, you are instead moving where the dots end up on the field.  For example, if you wanted to say change the label of dot 2 on SS2 with dot 3 on SS2, you could think it would be easy to just change the label indices.  But then their continuities don't match.  You really want to just invert that dot 2 is in the place of dot 3.

So I think the need for a label index may not exist.
