### ISSUE TITLE
Change the default branch from "master" to "main"

### ISSUE THREAD

**Issue by MichaelTamaki** [calband/calchart-redesign#110]
See docs for changing the default branch: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch

Update our Github workflow to only trigger the publish job on the "main" branch https://github.com/calband/calchart-redesign/blob/master/.github/workflows/node.js.yml#L31

**Comment by adhamrait** [comment]
Closed with #135
