### ISSUE TITLE
Use constants for VueX mutations

### ISSUE THREAD

**Issue by MichaelTamaki** [calband/calchart-redesign#82]
Implement the suggestions from the VueX guide below. We could consider creating an `enum` with every mutation type string. 

https://vuex.vuejs.org/guide/mutations.html#using-constants-for-mutation-types

See “Mutations” section from below link. I think it would be fine to just implement `MutationTypes` from this article. 

https://dev.to/3vilarthas/vuex-typescript-m4j

**Comment by rmpowell77** [comment]
will be addressed with #137 .
